{% set name = "consul-template" %}
{% set version = "0.19.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hashicorp/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: d10dbd1f332f1882c433f410a0704a84de405ba3068f285f9c23704701ee3d73  # [not win]

  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  fn: {{ name }}-{{ version }}.zip  # [win]
  sha256: 01a2d2979623efb95067251b569cc2020b36fbfafdca0e9cd6b4fb7f14805712  # [win64]

build:
  number: 0

requirements:
  build:
    - go 1.9.3  # [not win]
    - git  # [not win]
    - make  # [not win]
    - toolchain  # [not win]

test:
  commands:
    - {{ name|lower }} -v

about:
  home: https://github.com/hashicorp/consul-tempate
  license: MPL 2.0
  summary: Consul-template is a daemon that provides a convenient way to populate values from Consul into the file system.
  description: |
     Consul-template is a daemon that provides a convenient way to populate values from 
     Consul into the file system.

     The daemon consul-template queries a Consul or Vault cluster and updates any number 
     of specified templates on the file system. As an added bonus, it can optionally run 
     arbitrary commands when the update process completes. 

  doc_url: https://github.com/hashicorp/consul-template/blob/v{{ version }}/README.md

extra:
  recipe-maintainers:
    - sodre
