{% set name = "consul-template" %}
{% set version = "0.19.4" %}
{% set build_number = 0 %}
{% set sha256_osx = load_file_regex(
    load_file=name + "_" + version + "_SHA256SUMS",
    regex_pattern="(?m)^(?P<sha256>[0-9a-f]+)\\s+"+ name + "_" + version + "_darwin_amd64.zip$",
    from_recipe_dir=True)["sha256"] %}
{% set sha256_linux32 = load_file_regex(
    load_file=name + "_" + version + "_SHA256SUMS",
    regex_pattern="(?m)^(?P<sha256>[0-9a-f]+)\\s+"+ name + "_" + version + "_linux_386.zip$",
    from_recipe_dir=True)["sha256"] %}
{% set sha256_linux64 = load_file_regex(
    load_file=name + "_" + version + "_SHA256SUMS",
    regex_pattern="(?m)^(?P<sha256>[0-9a-f]+)\\s+"+ name + "_" + version + "_linux_amd64.zip$",
    from_recipe_dir=True)["sha256"] %}
{% set sha256_win32 = load_file_regex(
    load_file=name + "_" + version + "_SHA256SUMS",
    regex_pattern="(?m)^(?P<sha256>[0-9a-f]+)\\s+"+ name + "_" + version + "_windows_386.zip$",
    from_recipe_dir=True)["sha256"] %}
{% set sha256_win64 = load_file_regex(
    load_file=name + "_" + version + "_SHA256SUMS",
    regex_pattern="(?m)^(?P<sha256>[0-9a-f]+)\\s+"+ name + "_" + version + "_windows_amd64.zip$",
    from_recipe_dir=True)["sha256"] %}



package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_amd64.zip  # [linux64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_linux_386.zip  # [linux32]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_darwin_amd64.zip  # [osx]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_amd64.zip  # [win64]
  url: https://releases.hashicorp.com/{{ name }}/{{ version }}/{{ name }}_{{ version }}_windows_386.zip  # [win32]
  fn: {{ name }}-{{ version }}.zip
  sha256: {{ sha256_osx }}  # [osx]
  sha256: {{ sha256_linux32 }}  # [linux32]
  sha256: {{ sha256_linux64 }}  # [linux64]
  sha256: {{ sha256_win32 }}  # [win32]
  sha256: {{ sha256_win64 }}  # [win64]

build:
  number: {{ build_number }}

test:
  commands:
    - {{ name }} -v

about:
  home: https://github.com/hashicorp/consul-tempate
  license: MPL 2.0
  summary: Consul-template is a daemon that provides a convenient way to populate values from Consul into the file system.
  description: |
     Consul-template is a daemon that provides a convenient way to populate values from 
     Consul into the file system.

     The daemon consul-template queries a Consul or Vault cluster and updates any number 
     of specified templates on the file system. As an added bonus, it can optionally run 
     arbitrary commands when the update process completes. 

  doc_url: https://github.com/hashicorp/consul-template/blob/v{{ version }}/README.md

extra:
  recipe-maintainers:
    - sodre
