travis:
  secure:
    BINSTAR_TOKEN: A9oDRc7tQrAQQ0mLN/iQY594PtVcQtJa9JYk7sd4p84CNe6m28Pb+OR1oiGQt1HqKNmOUiPNIp4IQq2XMigTSXKEy0Zwi7Lzecrj5DbceAGsoK+gC556AhXB8CFQczHXu7Aiq72WA85HM7jpxRnZQdR7rdedZsRi8FHYsFg55JpNoiMcPrSc9uNB1KDxWJl5EBizsJUVx5mOrHxd8439emi5jADCMDL65mApoetVJEKzKn14S1aqB8DxsPSGdpm3uGRtPCT6UB6lrrCwrmD+BfYEz5MxgBcfp+WWrDgWmycUzUmK5dWStgqHwtplxQAANazqOs2GUeho3TZd5c44fA3LeaM3VKFm78Ow2JyLqsSU7XJwKCkvs8eY2fQjMhp6LhsISUd1K1fpjtsa8ObECkaD3F/pnWCikvjQulQODPT/cr8Y42zVPMfFfLdoQYMXldEQM2SF7Vn1ngpNTHwcTA415Xj4Un5DBZ+S6g1O7Hs6UvvD1BuJE5Ghef1ZRcDgNx4JrQCpIHO91MXbsgW0pPGX6ojDR9fCvghuPzR3unYUnIoAeFb1hhnrVEckuQWG86d8SNf1sgAkkQHtoLtsxU2+Ab+bWhhGXeKApHHNqLrHFEQLOFnxHy+iSmGri0cQxZfaDT2PJh3F3mNS4wojyphlmye6S4qLLzINqywPUiU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
